---
- name: install pack and satrt service
  hosts: all
  become: true 
  tasks: 
  - name: insatll httpd
    yum: 
     name: httpd 
     state: installed   
  - name: start httpd
    service:
      name: httpd
      state: started  
